version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test:
    executor: win/default     
    
    steps:
      - checkout
      - run: dotnet test
  publish:
    executor: win/default

    steps:
      - checkout
      - run: dotnet publish

